### ISSUE TITLE
can not load models

### ISSUE THREAD

**Issue by thisDy** [IricsDo/Data-Hidding-Using-GAN#2]
Hello,

As mentioned in your README, your models cannot be used directly, so I downloaded the models provided by the original author to the models directory in your project. However, they still don't seem to work. How can I resolve this issue?

Thank you.
![1719260147946](https://github.com/IricsDo/Data-Hidding-Using-GAN/assets/116807711/2ae3cd6a-9909-41c4-9750-569225c89900)

**Comment by IricsDo** [comment]
Thanks you for attention my project.
Have you install all module? If Yes, please send me the capture of terminal you run. It will be show the error and I can debug easily.

**Comment by ybL-123** [comment]
invalid literal for int() with base 2: 'TrueTrueTrueTrueTrueTrueTrueFalse'
Hello, I've finally encountered this issue. How can I resolve it? Thank you.

**Comment by IricsDo** [comment]
Oh, this error occurs when you use the incorrect PyTorch library. You must install the library follow requirement file I push in this repository. I know the library is too old but if you want to get it running, please follow my instructions. If not, you must manually update to the latest version.
Thank you

**Comment by IricsDo** [comment]
And you can follow my question 3 years ago in here: [https://discuss.pytorch.org/t/some-difference-between-pytorch-version-1-0-0-and-pytorch-version-1-7-1/122210](https://discuss.pytorch.org/t/some-difference-between-pytorch-version-1-0-0-and-pytorch-version-1-7-1/122210)

**Comment by ybL-123** [comment]
That's strange. I used the requirements file to install, maybe I should create a new virtual environment. Anyway, thank you.

Alright, I didn't know it was related to torch before. I thought using the pre-trained model wouldn't have any impact. Thank you for your response; it helped me a lot.

**Comment by IricsDo** [comment]
Ok, I will close this issue.
